spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_system
    username: devuser
    password: devuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "optional:configserver:http://localhost:8088"
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka